<?php
/**
 * Artistiya E-Commerce — Environment Configuration
 * Auto-generated by install.php
 * 
 * SECURITY: This file must NOT be accessible via web browser.
 * Add to .htaccess: <Files ".env.php"><Deny from all></Files>
 */

return [
    // Application
    'APP_NAME'    => 'Artistiya',
    'APP_ENV'     => 'production',  // production | staging | development
    'APP_DEBUG'   => false,
    'APP_URL'     => 'https://yourdomain.com',
    'APP_KEY'     => bin2hex(random_bytes(32)),  // Auto-generated, replace after install

    // Database
    'DB_HOST'     => 'localhost',
    'DB_PORT'     => '3306',
    'DB_NAME'     => 'artistiya_db',
    'DB_USER'     => 'root',
    'DB_PASS'     => '',

    // JWT Authentication
    'JWT_SECRET'  => bin2hex(random_bytes(32)),  // Auto-generated
    'JWT_EXPIRY'  => 86400 * 7,  // 7 days in seconds

    // Encryption (AES-256-CBC)
    'ENCRYPTION_KEY' => bin2hex(random_bytes(32)),  // 64-char hex

    // File Storage
    'STORAGE_PATH'   => __DIR__ . '/../storage',
    'UPLOAD_MAX_SIZE' => 20 * 1024 * 1024,  // 20MB
    'ALLOWED_EXTENSIONS' => ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf'],

    // Email (Hostinger SMTP default)
    'MAIL_DRIVER'   => 'smtp',
    'MAIL_HOST'     => 'smtp.hostinger.com',
    'MAIL_PORT'     => 465,
    'MAIL_USERNAME' => '',
    'MAIL_PASSWORD' => '',
    'MAIL_FROM'     => 'info@yourdomain.com',
    'MAIL_FROM_NAME' => 'Artistiya',
    'MAIL_ENCRYPTION' => 'ssl',

    // SMS (configure one provider)
    'SMS_PROVIDER'  => '',  // twilio | bulksmbd | greenweb | smsq | infobip
    'SMS_API_KEY'   => '',
    'SMS_API_SECRET' => '',
    'SMS_SENDER_ID' => 'Artistiya',

    // Payment Gateways
    'SSLCOMMERZ_STORE_ID'   => '',
    'SSLCOMMERZ_STORE_PASS' => '',
    'SSLCOMMERZ_SANDBOX'    => true,
    'BKASH_APP_KEY'         => '',
    'BKASH_APP_SECRET'      => '',
    'BKASH_USERNAME'        => '',
    'BKASH_PASSWORD'        => '',
    'BKASH_SANDBOX'         => true,

    // Delivery Providers
    'PATHAO_CLIENT_ID'     => '',
    'PATHAO_CLIENT_SECRET' => '',
    'PATHAO_USERNAME'      => '',
    'PATHAO_PASSWORD'      => '',
    'STEADFAST_API_KEY'    => '',
    'STEADFAST_SECRET_KEY' => '',

    // CORS
    'CORS_ALLOWED_ORIGINS' => ['https://yourdomain.com'],
    'CORS_ALLOWED_METHODS' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'CORS_ALLOWED_HEADERS' => ['Content-Type', 'Authorization', 'X-Requested-With'],
];
